### ISSUE TITLE
WAIC and loo-cv for glm models?

### ISSUE THREAD

**Issue by dr-jojo** [avehtari/modelselection_tutorial#3]
This is probably a stupid question but is it possible to get WAIC or loo-cv for a frequentist model? Say I make a logistic model in r with GLM,, obviously you can do AIC, but it is not as good. I have used loo package with the brms package so I know how do do that for bayseian models. But is it even possible for a frequentist one? Any help would be appreciated

**Comment by avehtari** [comment]
Oops, as github changed how to see new issues, I seem to have missed several issues for over two years. LOO-CV doesn't define yet what utility or loss is used, so it doesn't yet define that it would be specifically Bayesian. PSIS-LOO and WAIC implemented in loo package are only for Bayesian models with posterior distribution. I hope you've found what you need for frequentist case.
